stages:
  fetch_raw_data:
    cmd: python -m steps.fetch_raw_data --config_params_path config_params.yaml --verbose 0
    outs:
      - data/czech_data.jsonl

  fetch_translator:
    cmd: wget -O data/lid.176.bin https://dl.fbaipublicfiles.com/fasttext/supervised-models/lid.176.bin
    outs:
      - data/lid.176.bin
      
  prepare:
    cmd: python -m steps.prepare --config_params_path config_params.yaml --verbose 0
    deps:
      - steps/prepare.py
      - src/data_processing.py
      - src/utils.py
      - config_params.yaml
      - data/czech_data.jsonl
      - data/lid.176.bin

    outs:
      - data/clean_czech_data.jsonl
      - data/BPE_tokenizer.json
      - data/tokenizer

  train:
    cmd: python -m steps.train --config_params_path config_params.yaml --verbose 0
    deps:
      - steps/train.py
      - src/data_processing.py
      - src/model.py
      - src/utils.py
      - src/training.py
      - data/clean_czech_data.jsonl
      - config_params.yaml
    outs:
      - model/byam_step_final
      - model/model.pt

  evaluate:
    cmd: python -m steps.evaluate --config_params_path config_params.yaml --input_sequence "Počasí v Praze" 
    deps:
      - steps/evaluate.py
      - src/utils.py
      - model/byam_step_final
      - config_params.yaml

    outs:
      - evaluate_results.json
