name: GitHub Actions Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Repo Checkout
        uses: actions/checkout@v4

      - name: Python Set Up
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Requirements Install
        run: |
          pip install -r requirements.txt
          pip install --no-deps -r requirements_no_deps.txt
          pip install pytest
          pip install dvc
      
      - name: Set up Git LFS
        run: |
          git lfs install
          git lfs pull
      
      - name: DVC pull
        env:
          DAGSHUB_USER: ${{ secrets.DAGSHUB_USER }}
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          dvc pull

      - name: Tests Run
        run: pytest -v